### YamlMime:UniversalReference
items:
  - uid: azure-iot-common.TransportConfigured
    name: TransportConfigured
    fullName: TransportConfigured
    children: []
    langs:
      - typeScript
    type: class
    summary: Result returned when a transport is successfully configured.
    source:
      path: results.ts
      startLine: 130
      remote:
        path: common/core/src\results.ts
        repo: 'https://github.com/Azure/azure-iot-sdk-node.git'
        branch: doc-patches
    package: azure-iot-common
